### PR TITLE
hactoberfest_2022

### PR DESCRIPTION
**Pull request by Archithgandla**
Hey I have added stack using single queue program
can you please add my file in your repository with label hactoberfest

### CODE REVIEW

**Comment by H9660** [comment]
> Hey I have added stack using single queue program can you please add my file in your repository with label hactoberfest



> Change the file name to the name of the program and not stack.cpp .

**Comment by H9660** [comment]
> > Hey I have added stack using single queue program can you please add my file in your repository with label hactoberfest
> 
> > Change the file name to the name of the program and not stack.cpp .
Also add comments in the program.

**Comment by Archithgandla** [comment]
> > > Hey I have added stack using single queue program can you please add my file in your repository with label hactoberfest
> > 
> > 
> > > Change the file name to the name of the program and not stack.cpp .
> > > Hey @H9660 I have changed the name of the file, can please check and suggest any more changes if required

**Review by H9660 — COMMENTED** [review]
Nice!

**Pull request merged**
